### ISSUE TITLE
How to do multisig authentication

### ISSUE THREAD

**Issue by brianorwhatever** [bcgov/trustdidweb#2]
If we want to allow multisig authentications of rotations how is this accomplished?

**Comment by andrewwhitehead** [comment]
Apart from the multi-controller authentication in #3, a DID document could make use of the [verifiable conditions](https://github.com/w3c-ccg/verifiable-conditions) verification method. In this case, I don't believe one or more external controllers should be listed at the top level of the document.

The DID document should list a verificationMethod of type `ConditionalProof2022`, referenced in the `authentication` block, with the controller set to the current DID. Nested in the `conditionAnd`, `conditionOr` etc blocks might be other verification methods with `controller` set to external DIDs, or references to other methods contained in the DID document. For keys controlled by other DID subjects, I believe those same keys should be repeated in the external DID document in order to assert ownership of the key. I'm curious why they disallow references to external keys.

**Comment by andrewwhitehead** [comment]
An example – note that the external keys must be repeated in the documents for `did:indy:network:parent1` and `did:example:parent2` respectively:

```json
{
    "@context": [
        "https://www.w3.org/ns/did/v1",
        "https://example.com/did/conditions-proof/v1"
    ],
    "id": "did:webnext:domain:skid",
    "versionId": 0,
    "authentication": ["#1"],
    "verificationMethod": [{
        "id": "#1",
        "controller": "did:webnext:domain:skid",
        "type": "ConditionalProof2022",
        "conditionAnd": [{
            "id": "did:indy:network:parent1#1",
            "controller": "did:indy:network:parent1",
            "type": "Ed25519VerificationKey2018",
            "publicKeyBase58": "PZ8Tyr4Nx8MHsRAGMpZmZ6TWY63dXWSCzamP7YTHkZc78MJgqWsAy"
        },
        {
            "id": "did:example:parent2#1",
            "controller": "did:example:parent2",
            "type": "Ed25519VerificationKey2018",
            "publicKeyBase58": "PZ8Tyr4Nx8MHsRAGMpZmZ6TWY63dXWSCzamP7YTHkZc78MJgqWsAy"
        }]
    }],
    "proof": [{
        "type": "JsonWebSignature2020",
        "created": "2020-02-15T17:13:18Z",
        "verificationMethod": "did:indy:network:parent1#1",
        "proofPurpose": "assertionMethod",
        "jws": "eyJiNjQiOmZhbHNlLCJjcm..1JX32CA9MkFHkmNprcNj9Da4Q4QOl0cY3obF8cdDRdnKr0IwNrAw"
    }, {
        "type": "JsonWebSignature2020",
        "created": "2020-02-15T17:13:18Z",
        "verificationMethod": "did:example:parent2#1",
        "proofPurpose": "assertionMethod",
        "jws": "53Fm3mYG9ZJWwRDgyTt9a..XVPC1X2ZRgGHdBHmUhYM4CVt6v4uV4JZ51PWxnB31bM9VvVjaVWu"
    }]
}
```

**Comment by swcurran** [comment]
Agree on the use of verifableCondition as the mechanism. See comment in #3 about this.

**Comment by swcurran** [comment]
Moved this out of the spec and leaving it to the management of the entries to the `updateKeys` to handle any necessary multi-sig management.
