### ISSUE TITLE
Extension Question

### ISSUE THREAD

**Issue by andywoodruff6** [bcgov/trustdidweb#89]
I did not find another place to ask a question about the spec other than here, so if there is a better place, I will move my question there.

I am looking to have some additional information stored in the DID doc. This information would likely be a combination of some string fields and integer fields. The exact information is not locked down yet. 

That being said I see that under [DID Method Parameters](https://bcgov.github.io/trustdidweb/#didtdw-did-method-parameters), the wording implies that only the listed parameters are valid for this did method and that I would not be allowed to extend it and add additional parameters. 

Is that an accurate statement? 

Thanks, 
Andy

**Comment by swcurran** [comment]
I’m not quite clear on the question, so I’ll define how I understand it, and you can confirm. I think you are asking:

You want to be able to put extra information, beyond what is defined in the DID Core Spec into the DIDDoc, and you are wondering if that is permitted/defined in `did:tdw`?  If that is the question, the answer is yes, you can do that.  The DID Controller can put anything into the DIDDoc, and that content will be resolved by anyone resolving the DID.  What you put into the DIDDoc **SHOULD** be either defined in the DID Core Spec or in the DID Registry so that it is understood by those resolving the DID.

The `parameters` are for controlling how `did:tdw` resolution works, and so does not impact the content of the DIDDoc. Those parameters define how a resolver should verify each DID log entry in resolving the DID.

Does that help?

**Comment by andywoodruff6** [comment]
Yes that answered my question. Thank you for clarifying.
